services:
  db:
    image: mysql:8.0
    container_name: bars_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: bars_db
      MYSQL_USER: diego
      MYSQL_PASSWORD: 12345
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-udiego", "-p12345"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 180s # Tiempo en que mysql inicia

  app: # almacena la aplicacion 
    build: .
    container_name: bars_flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: diego
      MYSQL_PASSWORD: 12345
      MYSQL_DB: bars_db
      SECRET_KEY: ADMINISTRADOR 
    depends_on:
      db: 
        condition: service_healthy

    restart: unless-stopped
    

volumes:
  mysql_data: