services:
  db:
    image: mysql:8.0
    container_name: bars_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: bars_db
      MYSQL_USER: diego
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck: # ¡Añade esto!
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "diego", "-p12345"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Dale tiempo para que el servidor MySQL inicie

  app: # Este servicio lo usaremos más tarde para la aplicación Flask
    build: .
    container_name: bars_flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: diego
      MYSQL_PASSWORD: 12345
      MYSQL_DB: bars_db
      SECRET_KEY: ADMINISTRADOR # Considera usar variables de entorno de Docker
    depends_on:
      db: # ¡Aquí es donde cambia! Es un diccionario donde la clave es el nombre del servicio
        condition: service_healthy

    restart: unless-stopped
    

volumes:
  mysql_data: